# Auto Gradient in TF
## Tensors & Variables in TF for Gradient Descent

M. Amintoosi

In [1]:
import tensorflow as tf

c:\Users\hp\.conda\envs\p310\lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.12.2 when it was built against 1.12.1, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "


<div dir="rtl">
تفاوت Tensor و Variable:

1. tf.Variable: معمولاً برای نگهداری وزن‌ها و بایاس‌ها در شبکه‌های عصبی استفاده می‌شود. یک متغیر قابل تغییر است ولی با استفاده از عملگرهای خاص به روزرسانی میشود. 

2. tf.Tensor: معمولاً به عنوان ورودی یا خروجی به لایه‌ها و عملگرها مورد استفاده قرار می‌گیرد.
</div>

## Auto gradient using Variables

In [2]:
x = tf.Variable(0.0)
print(x)
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)
print(y, grad_of_y_wrt_x)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(2.0, shape=(), dtype=float32)


## Auto gradient using Tensors

In [3]:
x = tf.convert_to_tensor(0.0)
print(x)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)
print(x, grad_of_y_wrt_x)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32) tf.Tensor(2.0, shape=(), dtype=float32)


تبدیل مقادیر عددی معمولی  به تنسور

In [4]:
x = 3.0
y = 2*x
w = 0.5
x, y, w = [tf.convert_to_tensor(float(a)) for a in [x, y, w]]
x, y, w

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5>)

<div dir="rtl">

## الگوریتم گرادیان کاهشی با تنسورها

در مدل زیر 
$x$
و
$y$
معلوم هستند، هدف پیدا کردن  ضریب 
$x$
هست:
</div>

$$
\large y = 2x 
$$

<div dir="rtl">

به فرض
$x\times w$
خروجی نورون هست،‌ به دنبال 
$w$ی بهینه هستیم

</div>

$$
\large error = wx - y
$$

$$
\large
\begin{aligned}
Loss &= {error}^2
= (w x - y)^2
\end{aligned}
$$

<div dir = "rtl">
کافیست از یک نقطه تصادفی شروع و در خلاف جهت مشتق تابع ضرر حرکت کنیم
</div>

$$
\large
\begin{aligned}
w = w - \eta \frac{\partial{Loss}}{\partial{w}}
\end{aligned}
$$

In [5]:
x = tf.convert_to_tensor(3.0)
y = tf.convert_to_tensor(6.0)
w = tf.convert_to_tensor(0.5)
for _ in range(20):
    with tf.GradientTape() as tape:
        tape.watch(w)
        loss = (w * x - y) ** 2
    grad_loss = tape.gradient(loss, w)
    w -= 0.01 * grad_loss
    print("Loss = {:05.2f},  w = {:05.2f} ".format(loss.numpy(), w.numpy()))

Loss = 20.25,  w = 00.77 
Loss = 13.62,  w = 00.99 
Loss = 09.16,  w = 01.17 
Loss = 06.16,  w = 01.32 
Loss = 04.14,  w = 01.44 
Loss = 02.78,  w = 01.54 
Loss = 01.87,  w = 01.63 
Loss = 01.26,  w = 01.69 
Loss = 00.85,  w = 01.75 
Loss = 00.57,  w = 01.79 
Loss = 00.38,  w = 01.83 
Loss = 00.26,  w = 01.86 
Loss = 00.17,  w = 01.89 
Loss = 00.12,  w = 01.91 
Loss = 00.08,  w = 01.92 
Loss = 00.05,  w = 01.94 
Loss = 00.04,  w = 01.95 
Loss = 00.02,  w = 01.96 
Loss = 00.02,  w = 01.97 
Loss = 00.01,  w = 01.97 


مشتق‌گیری برحسب ایکس به جای دبلیو

In [6]:
x = tf.convert_to_tensor(3.0)
y = tf.convert_to_tensor(6.0)
w = tf.convert_to_tensor(0.5)
for _ in range(100):
    with tf.GradientTape() as tape:
        tape.watch(x)
        loss = (w * x - y) ** 2
    grad_loss = tape.gradient(loss, x)
    x -= 0.1 * grad_loss
    print("Loss = {:05.2f},  x = {:05.2f} ".format(loss.numpy(), x.numpy()))

Loss = 20.25,  x = 03.45 
Loss = 18.28,  x = 03.88 
Loss = 16.49,  x = 04.28 
Loss = 14.89,  x = 04.67 
Loss = 13.43,  x = 05.04 
Loss = 12.12,  x = 05.38 
Loss = 10.94,  x = 05.71 
Loss = 09.88,  x = 06.03 
Loss = 08.91,  x = 06.33 
Loss = 08.04,  x = 06.61 
Loss = 07.26,  x = 06.88 
Loss = 06.55,  x = 07.14 
Loss = 05.91,  x = 07.38 
Loss = 05.34,  x = 07.61 
Loss = 04.82,  x = 07.83 
Loss = 04.35,  x = 08.04 
Loss = 03.92,  x = 08.24 
Loss = 03.54,  x = 08.43 
Loss = 03.20,  x = 08.60 
Loss = 02.88,  x = 08.77 
Loss = 02.60,  x = 08.93 
Loss = 02.35,  x = 09.09 
Loss = 02.12,  x = 09.23 
Loss = 01.91,  x = 09.37 
Loss = 01.73,  x = 09.50 
Loss = 01.56,  x = 09.63 
Loss = 01.41,  x = 09.75 
Loss = 01.27,  x = 09.86 
Loss = 01.15,  x = 09.97 
Loss = 01.03,  x = 10.07 
Loss = 00.93,  x = 10.16 
Loss = 00.84,  x = 10.26 
Loss = 00.76,  x = 10.34 
Loss = 00.69,  x = 10.43 
Loss = 00.62,  x = 10.51 
Loss = 00.56,  x = 10.58 
Loss = 00.50,  x = 10.65 
Loss = 00.45,  x = 10.72 
Loss = 00.41

## Using tf.Variable

Again grad wrt w

In [7]:
# x = tf.convert_to_tensor(3.0)
# y = tf.convert_to_tensor(6.0)
# w = tf.Variable(0.5)

x = tf.constant(3.0)
y = tf.constant(6.0)
w = tf.Variable(0.5)
for _ in range(20):
    with tf.GradientTape() as tape:
        tape.watch(x)
        loss = (w * x - y) ** 2
    grad_loss = tape.gradient(loss, w)
    w.assign_sub(0.01 * grad_loss)
    print("Loss = {:05.2f},  w = {:05.2f} ".format(loss.numpy(), w.numpy()))

Loss = 20.25,  w = 00.77 
Loss = 13.62,  w = 00.99 
Loss = 09.16,  w = 01.17 
Loss = 06.16,  w = 01.32 
Loss = 04.14,  w = 01.44 
Loss = 02.78,  w = 01.54 
Loss = 01.87,  w = 01.63 
Loss = 01.26,  w = 01.69 
Loss = 00.85,  w = 01.75 
Loss = 00.57,  w = 01.79 
Loss = 00.38,  w = 01.83 
Loss = 00.26,  w = 01.86 
Loss = 00.17,  w = 01.89 
Loss = 00.12,  w = 01.91 
Loss = 00.08,  w = 01.92 
Loss = 00.05,  w = 01.94 
Loss = 00.04,  w = 01.95 
Loss = 00.02,  w = 01.96 
Loss = 00.02,  w = 01.97 
Loss = 00.01,  w = 01.97 
