M. Amintoosi

# Play with Conv layers and filters

In [85]:
import keras
from keras import layers
from keras import models
import tensorflow as tf
import numpy as np

keras.__version__

'2.14.0'

In [86]:
n_channels = 1
n_filters = 1
model = models.Sequential()
model.add(layers.Conv2D(n_filters, (3, 3), input_shape=(3, 3, n_channels)))

In [87]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_9 (Conv2D)           (None, 1, 1, 1)           10        
                                                                 
Total params: 10 (40.00 Byte)
Trainable params: 10 (40.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [88]:
model.layers[0].get_weights()[0].shape, model.layers[0].get_weights()[0]

((3, 3, 1, 1),
 array([[[[-0.5267342 ]],
 
         [[-0.5311715 ]],
 
         [[ 0.5145925 ]]],
 
 
        [[[ 0.453048  ]],
 
         [[-0.19120044]],
 
         [[-0.50300837]]],
 
 
        [[[-0.33497047]],
 
         [[ 0.16212177]],
 
         [[ 0.11044431]]]], dtype=float32))

The difference between model.weights and model.layers[i].get_weights() in TF is that model.weights returns a list of all the weights and biases of the model, while model.layers[i].get_weights() returns a list of the weights and biases of the i-th layer of the model.

In [89]:
model.weights

[<tf.Variable 'conv2d_9/kernel:0' shape=(3, 3, 1, 1) dtype=float32, numpy=
 array([[[[-0.5267342 ]],
 
         [[-0.5311715 ]],
 
         [[ 0.5145925 ]]],
 
 
        [[[ 0.453048  ]],
 
         [[-0.19120044]],
 
         [[-0.50300837]]],
 
 
        [[[-0.33497047]],
 
         [[ 0.16212177]],
 
         [[ 0.11044431]]]], dtype=float32)>,
 <tf.Variable 'conv2d_9/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [90]:
input = np.random.randint(0, 10, size=(3, 3, n_channels))
input.shape, input, input[:,:,0]

((3, 3, 1),
 array([[[0],
         [4],
         [0]],
 
        [[2],
         [1],
         [9]],
 
        [[7],
         [1],
         [9]]]),
 array([[0, 4, 0],
        [2, 1, 9],
        [7, 1, 9]]))

In [91]:
# model.predict(input)

In [92]:
x = input[np.newaxis,:,:,:]
x.shape

(1, 3, 3, 1)

In [93]:
model.predict(x)

1/1 [==============================] - 0s 56ms/step


array([[[[-7.125539]]]], dtype=float32)

In [94]:
w = model.weights[0]
w.shape

TensorShape([3, 3, 1, 1])

In [95]:
w = np.squeeze(w, axis=(2, 3))
w.shape, w

((3, 3),
 array([[-0.5267342 , -0.5311715 ,  0.5145925 ],
        [ 0.453048  , -0.19120044, -0.50300837],
        [-0.33497047,  0.16212177,  0.11044431]], dtype=float32))

In [96]:
np.sum(input[:,:,0]*w)

-7.125538527965546

تغییر تعداد کانال‌های رنگ ورودی

In [97]:
n_channels = 2
n_filters = 1
model = models.Sequential()
model.add(layers.Conv2D(n_filters, (3, 3), input_shape=(3, 3, n_channels)))
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_10 (Conv2D)          (None, 1, 1, 1)           19        
                                                                 
Total params: 19 (76.00 Byte)
Trainable params: 19 (76.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [98]:
input = np.random.randint(0, 10, size=(3, 3, n_channels))
input.shape, input[:,:,0]

((3, 3, 2),
 array([[2, 6, 1],
        [1, 0, 7],
        [8, 1, 1]]))

In [99]:
x = input[np.newaxis,:,:,:]
# x.shape
model.predict(x)

1/1 [==============================] - 0s 182ms/step


array([[[[2.0529406]]]], dtype=float32)

In [100]:
w = model.weights[0]
w.shape

TensorShape([3, 3, 2, 1])

In [101]:
w = np.squeeze(w)
w.shape, w

((3, 3, 2),
 array([[[-0.35773772, -0.27180827],
         [ 0.01903328, -0.00075549],
         [ 0.32946035, -0.25483716]],
 
        [[ 0.03442004, -0.45545053],
         [-0.05410364,  0.3932884 ],
         [-0.23828074, -0.33123094]],
 
        [[ 0.2905381 ,  0.37793425],
         [ 0.2984381 , -0.1826269 ],
         [-0.35273024,  0.28576055]]], dtype=float32))

In [102]:
np.sum(input*w)

2.052940219640732