# Gradient Descent

M. Amintoosi

In [ ]:
import tensorflow as tf

<div dir="rtl">
تفاوت Tensor و Variable:

1. tf.Variable: یک متغیر قابل تغییر است که مقدار آن در طول زمان در مدل TensorFlow قابل تغییر است. متغیرها در TensorFlow می‌توانند مقدار داشته باشند که در حین آموزش تغییر می‌کند. می‌توانند با استفاده از عملگرهایی مانند افزایش و کاهش مقدار، به روزرسانی شوند. معمولاً tf.Variable برای نگهداری وزن‌ها و بایاس‌ها در شبکه‌های عصبی استفاده می‌شود.

2. tf.Tensor: نمایش‌دهنده یک جریان داده است که در ساختارهای داده چند بعدی به کار می‌رود. tf.Tensor مقادیر تنسور را در خود نگه‌داری می‌کند و تبدیل‌های ریاضی و منطقی روی آنها اعمال می‌کند. معمولاً tf.Tensor نتیجه‌ی تحلیل یا محاسباتی در TensorFlow است که به عنوان ورودی یا خروجی به لایه‌ها و عملگرها مورد استفاده قرار می‌گیرد.
</div>

## Auto gradient using Variables

In [78]:
x = tf.Variable(0.0)
print(x)
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)
print(y, grad_of_y_wrt_x)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(2.0, shape=(), dtype=float32)


## Auto gradient using Tensors

In [77]:
x = tf.convert_to_tensor(0.0)
print(x)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)
print(x,grad_of_y_wrt_x)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32) tf.Tensor(2.0, shape=(), dtype=float32)


تبدیل مقادیر عددی معمولی  به تنسور

In [27]:
x = 3.0
o = -x
w = 0.5
x, o, w = [tf.convert_to_tensor(float(a)) for a in [x, o, w]]
x, o, w

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5>)

الگوریتم گرادیان کاهشی با تنسورها

In [89]:
x = tf.convert_to_tensor(3.0)
w = tf.convert_to_tensor(0.5)
o = tf.convert_to_tensor(-3.0)
for _ in range(20):
    with tf.GradientTape() as tape:
        tape.watch(w)
        loss = (o - w * x) ** 2
    grad_loss = tape.gradient(loss, w)
    w -= 0.01 * grad_loss
    print("Loss = {:05.2f},  w = {:05.2f} ".format(loss.numpy(), w.numpy()))

Loss = 20.25,  w = 00.23 
Loss = 13.62,  w = 00.01 
Loss = 09.16,  w = -0.17 
Loss = 06.16,  w = -0.32 
Loss = 04.14,  w = -0.44 
Loss = 02.78,  w = -0.54 
Loss = 01.87,  w = -0.63 
Loss = 01.26,  w = -0.69 
Loss = 00.85,  w = -0.75 
Loss = 00.57,  w = -0.79 
Loss = 00.38,  w = -0.83 
Loss = 00.26,  w = -0.86 
Loss = 00.17,  w = -0.89 
Loss = 00.12,  w = -0.91 
Loss = 00.08,  w = -0.92 
Loss = 00.05,  w = -0.94 
Loss = 00.04,  w = -0.95 
Loss = 00.02,  w = -0.96 
Loss = 00.02,  w = -0.97 
Loss = 00.01,  w = -0.97 


مشتق‌گیری برحسب ایکس به جای دبلیو

In [90]:
x = tf.convert_to_tensor(3.0)
w = tf.convert_to_tensor(0.5)
o = tf.convert_to_tensor(-3.0)
for _ in range(100):
    with tf.GradientTape() as tape:
        tape.watch(x)
        loss = (o - w * x) ** 2
    grad_loss = tape.gradient(loss, x)
    x -= 0.1 * grad_loss
    print("Loss = {:05.2f},  x = {:05.2f} ".format(loss.numpy(), x.numpy()))

Loss = 20.25,  x = 02.55 
Loss = 18.28,  x = 02.12 
Loss = 16.49,  x = 01.72 
Loss = 14.89,  x = 01.33 
Loss = 13.43,  x = 00.96 
Loss = 12.12,  x = 00.62 
Loss = 10.94,  x = 00.29 
Loss = 09.88,  x = -0.03 
Loss = 08.91,  x = -0.33 
Loss = 08.04,  x = -0.61 
Loss = 07.26,  x = -0.88 
Loss = 06.55,  x = -1.14 
Loss = 05.91,  x = -1.38 
Loss = 05.34,  x = -1.61 
Loss = 04.82,  x = -1.83 
Loss = 04.35,  x = -2.04 
Loss = 03.92,  x = -2.24 
Loss = 03.54,  x = -2.43 
Loss = 03.20,  x = -2.60 
Loss = 02.88,  x = -2.77 
Loss = 02.60,  x = -2.93 
Loss = 02.35,  x = -3.09 
Loss = 02.12,  x = -3.23 
Loss = 01.91,  x = -3.37 
Loss = 01.73,  x = -3.50 
Loss = 01.56,  x = -3.63 
Loss = 01.41,  x = -3.75 
Loss = 01.27,  x = -3.86 
Loss = 01.15,  x = -3.97 
Loss = 01.03,  x = -4.07 
Loss = 00.93,  x = -4.16 
Loss = 00.84,  x = -4.26 
Loss = 00.76,  x = -4.34 
Loss = 00.69,  x = -4.43 
Loss = 00.62,  x = -4.51 
Loss = 00.56,  x = -4.58 
Loss = 00.50,  x = -4.65 
Loss = 00.45,  x = -4.72 
Loss = 00.41

## Using tf.Variable

Again grad wrt w

In [103]:
# x = tf.convert_to_tensor(3.0)
# w = tf.Variable(0.5)
# o = tf.convert_to_tensor(-3.0)

x = tf.constant(3.0)
w = tf.Variable(0.5)
o = tf.constant(-3.0)
for _ in range(20):
    with tf.GradientTape() as tape:
        tape.watch(x)
        loss = (o - w * x) ** 2
    grad_loss = tape.gradient(loss, w)
    w.assign_sub(0.01 * grad_loss)
    print("Loss = {:05.2f},  w = {:05.2f} ".format(loss.numpy(), w.numpy()))

Loss = 20.25,  w = 00.23 
Loss = 13.62,  w = 00.01 
Loss = 09.16,  w = -0.17 
Loss = 06.16,  w = -0.32 
Loss = 04.14,  w = -0.44 
Loss = 02.78,  w = -0.54 
Loss = 01.87,  w = -0.63 
Loss = 01.26,  w = -0.69 
Loss = 00.85,  w = -0.75 
Loss = 00.57,  w = -0.79 
Loss = 00.38,  w = -0.83 
Loss = 00.26,  w = -0.86 
Loss = 00.17,  w = -0.89 
Loss = 00.12,  w = -0.91 
Loss = 00.08,  w = -0.92 
Loss = 00.05,  w = -0.94 
Loss = 00.04,  w = -0.95 
Loss = 00.02,  w = -0.96 
Loss = 00.02,  w = -0.97 
Loss = 00.01,  w = -0.97 


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>